# Generated by Django 6.0 on 2026-06-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tradition',
            field=models.CharField(blank=True, default='universal', max_length=20),
        ),
    ]
